# Generated by Django 3.2 on 2021-05-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=255, verbose_name='Product Name')),
                ('PRDDesc', models.TextField(verbose_name='Product Description')),
                ('PRDCategory', models.CharField(max_length=255, verbose_name='Product Category')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product price')),
                ('PRDCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost')),
                ('PRDImage', models.ImageField(upload_to='product', verbose_name='Product Image')),
                ('PRDCreatedAt', models.DateTimeField(max_length=255, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALAlternatives', models.ManyToManyField(related_name='Alternative_prodects', to='product.Product')),
                ('PALProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_prodect', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=255, verbose_name='Category Name')),
                ('CATDesc', models.TextField(verbose_name='Category Description')),
                ('CATImg', models.ImageField(upload_to='category', verbose_name='Category Image')),
                ('CATCreatedAt', models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Created At')),
                ('CATSub_Category', models.ForeignKey(blank=True, limit_choices_to={'CATSub_Category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category Sub-Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
