# Generated by Django 3.2 on 2021-05-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_accesories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_accesories',
            name='ACCAlternatives',
            field=models.ManyToManyField(related_name='Accesories_prodects', to='product.Product', verbose_name='Accesories'),
        ),
        migrations.AlterField(
            model_name='product_accesories',
            name='ACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Accesorie_prodect', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALAlternatives',
            field=models.ManyToManyField(related_name='Alternative_prodects', to='product.Product', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_prodect', to='product.product', verbose_name='Product'),
        ),
    ]
