# Generated by Django 3.2 on 2021-05-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_prdcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Product Category'),
        ),
    ]
