# Generated by Django 3.2 on 2021-05-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_prdcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDBrand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDCategory',
        ),
    ]
