# Generated by Django 3.2 on 2021-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210505_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Product Cost'),
        ),
    ]
